appearance:
  color: green
  name: IMADE3D-OctoPrint
  components:
    order:
      tab:
      - temperature
      - control
      - gcodeviewer
      - terminal
      - plugin_slicer
      - timelapse
      - plugin_filemanager
      - plugin_stats
      - plugin_bedlevelvisualizer
plugins:
  BetterHeaterTimeout:
    _config_version: 2
  TerminalCommands:
    controls:
    - commands: M290 Z-0.1
      name: Live adjust Z -0.10
    - commands: M290 Z-0.05
      name: Live adjust Z -0.05
    - commands: M290 Z0.05
      name: Live adjust Z +0.05
    - commands: M290 Z0.1
      name: Live adjust Z +0.10
  bedlevelvisualizer:
    command: 'M155 S30

      @BEDLEVELVISUALIZER

      M420 V

      M155 S3'
  announcements:
    _config_version: 1
  curalegacy:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  firmwareupdater:
    avrdude_avrmcu: m2560
    avrdude_baudrate: '115200'
    avrdude_path: /usr/bin/avrdude
    avrdude_programmer: wiring
    enable_postflash_commandline: false
    enable_postflash_delay: false
    enable_postflash_gcode: false
    enable_preflash_commandline: false
    flash_method: avrdude
    postflash_commandline: ''
    postflash_delay: '20'
    postflash_gcode: M117 Firmware updated!;M501;M500
    preflash_commandline: ''
  simpleemergencystop:
    confirmationDialog: true
  ipOnConnect:
    delay: '18'
    displayTime: '60'
  portlister:
    autoconnect_delay: 10
  softwareupdate:
    _config_version: 6
    check_providers:
      BetterHeaterTimeout: BetterHeaterTimeout
      GcodeEditor: GcodeEditor
      TerminalCommands: TerminalCommands
      autoscroll: autoscroll
      autoselect: autoselect
      curalegacy: curalegacy
      filemanager: filemanager
      firmwareupdater: firmwareupdater
      fullscreen: fullscreen
      ipOnConnect: ipOnConnect
      portlister: portlister
      requestspinner: requestspinner
      simpleemergencystop: simpleemergencystop
      slicer: slicer
      stats: stats
      taborder: taborder
      tempsgraph: tempsgraph
  taborder:
    _config_version: 4
    tabs:
    - icon: fas fa-thermometer-quarter
      icon_color: '#5e5e5e'
      icon_tooltip: Temperature
      name: temperature
      showtext: true
    - icon: fas fa-arrows-alt
      icon_color: '#5e5e5e'
      icon_tooltip: Control
      name: control
      showtext: true
    - icon: fas fa-eye
      icon_color: '#5e5e5e'
      icon_tooltip: Gcode Viewer
      name: gcodeviewer
      showtext: true
    - icon: fas fa-terminal
      icon_color: '#5e5e5e'
      icon_tooltip: Terminal
      name: terminal
      showtext: true
    - icon: fas fa-layer-group
      icon_color: '#5e5e5e'
      icon_tooltip: Slicer
      name: plugin_slicer
      showtext: true
    - icon: fas fa-images
      icon_color: '#5e5e5e'
      icon_tooltip: Timelapse
      name: timelapse
      showtext: true
    - icon: fas fa-server
      icon_color: '#5e5e5e'
      icon_tooltip: File Manager
      name: plugin_filemanager
      showtext: true
    - icon: fas fa-chart-pie
      icon_color: '#5e5e5e'
      icon_tooltip: Printer Stats
      name: plugin_stats
      showtext: true
    - icon: fas fa-chart-area
      icon_color: '#5e5e5e'
      icon_tooltip: Bed Visualizer
      name: plugin_bedlevelvisualizer
      showtext: true
  tempsgraph:
    startWithAutoScale: true
printerProfiles:
  default: jellybox_2
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/ttyACM0
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart
  pluginBlacklist:
    enabled: true
slicing:
  defaultProfiles:
    cura: pla_0.2_medium_curalegacy
temperature:
  cutoff: 60
  profiles:
  - bed: 20
    extruder: 180
    name: Universal Preheat
  - bed: 60
    extruder: 210
    name: PLA
  - bed: 70
    extruder: 230
    name: PETG
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv