appearance:
  color: green
  name: IMADE3D-OctoPrint
plugins:
  BetterHeaterTimeout:
    _config_version: 2
  TerminalCommands:
    controls:
    - commands: M290 Z-0.1
      name: Live adjust Z -0.10
    - commands: M290 Z-0.05
      name: Live adjust Z -0.05
    - commands: M290 Z0.05
      name: Live adjust Z +0.05
    - commands: M290 Z0.1
      name: Live adjust Z +0.10
  announcements:
    _config_version: 1
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  firmwareupdater:
    avrdude_avrmcu: m2560
    avrdude_baudrate: '115200'
    avrdude_path: /usr/bin/avrdude
    avrdude_programmer: wiring
    enable_postflash_commandline: false
    enable_postflash_delay: false
    enable_postflash_gcode: false
    enable_preflash_commandline: false
    flash_method: avrdude
    postflash_commandline: ''
    postflash_delay: '20'
    postflash_gcode: M117 Firmware updated!;M501;M500
    preflash_commandline: ''
  simpleemergencystop:
    confirmationDialog: true
  ipOnConnect:
    delay: '18'
    displayTime: '60'
  portlister:
    autoconnect_delay: 10
  softwareupdate:
    _config_version: 6
    check_providers:
      BetterHeaterTimeout: BetterHeaterTimeout
      GcodeEditor: GcodeEditor
      TerminalCommands: TerminalCommands
      autoscroll: autoscroll
      autoselect: autoselect
      curalegacy: curalegacy
      filemanager: filemanager
      firmwareupdater: firmwareupdater
      fullscreen: fullscreen
      ipOnConnect: ipOnConnect
      portlister: portlister
      requestspinner: requestspinner
      simpleemergencystop: simpleemergencystop
      slicer: slicer
      tempsgraph: tempsgraph
  tempsgraph:
    startWithAutoScale: true
printerProfiles:
  default: jellybox_2
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/ttyACM0
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart
  pluginBlacklist:
    enabled: true
slicing:
  defaultProfiles:
    cura: pla_0.3_coarse_curalegacy
temperature:
  cutoff: 60
  profiles:
  - bed: 20
    extruder: 180
    name: Universal Preheat
  - bed: 60
    extruder: 210
    name: PLA
  - bed: 70
    extruder: 230
    name: PETG
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv